### ISSUE TITLE
How to open a db in readonly mode?

### ISSUE THREAD

**Issue by hythm7** [CurtTilmes/perl6-dbsqlite#11]
I tried to pass the filename as `file:db.sqlite?mode=ro` but I get `out of memory` error.

**Comment by CurtTilmes** [comment]
That capability (and URI filenames in general) aren't yet implemented. 

I'll try to add them when I get around to it.  (Patches welcome!)

**Comment by hythm7** [comment]
Tried to implement it in this [branch](https://github.com/hythm7/raku-dbsqlite/tree/enh-open-flags) but doesn't pass the [test](https://github.com/hythm7/raku-dbsqlite/blob/enh-open-flags/t/01-native.t#L16) I added for `sqlite3_open_v2`, and dies with the `out of memory` error. Not sure what I'm missing. Any suggestion?

**Comment by CurtTilmes** [comment]
There was a bug in the error reporting that didn't convert the code to string properly resulting in "out of memory".  I copied your stuff and did it slightly differently.

**Comment by hythm7** [comment]
Thank you!
