### ISSUE TITLE
The module fails to install due to hard-coded NativeLibs version

### ISSUE THREAD

**Issue by vrurg** [CurtTilmes/perl6-dbsqlite#12]
`NativeLibs` has been updated recently to v0.0.8. `DB::SQLite` depends specifically on v0.0.7 and consequently fails to install since Oct 16 when the dependency has been updated. I tried removing version adverb from the `use` statement in the code and testing. Tests are passing ok. Perhaps it worth leaving the version in META6 only and have it in `0.0.7+` form?

**Comment by CurtTilmes** [comment]
changed as suggested
